### ISSUE TITLE
Installation processs of DNS

### ISSUE THREAD

**Issue by arun81** [stellarproject/atlas#1]
Hi 

Please help us with the installation process in linux and what are the pre-requiste required 

Thanks

**Comment by ehazlett** [comment]
I'll add some better docs soon but for now I've created a master build available [here](https://ehazlett-public.s3.us-east-2.amazonaws.com/atlas/atlas-linux-latest.tar.gz).  Extract this to somewhere on your path and follow the usage instructions in the readme.

I'll update the github actions to add autobuild releases and better docs.

Thanks!

**Comment by arun81** [comment]
Thanks.....

**Comment by ehazlett** [comment]
Installation docs along with autobuilds for Docker images and binaries are now available (https://github.com/ehazlett/atlas#installation).

Thanks!
